import Header from "@/components/auth/AuthHeader";
import LisyiHui from "@/components/auth/LisyiHui";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

    return (

      <section className="w-screen h-screen flex items-center justify-center">

        <LisyiHui></LisyiHui>
        
        
        {children}

        <Header></Header>

      </section>
    );
  }