import Header from "@/components/main/Header";
import NavButton from "@/components/NavButoon";
import type { Metadata } from "next";
import Image from "next/image";
import { useRouter } from 'next/navigation';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

    return (

      <section className="w-screen h-screen flex items-center justify-center">
        
        {children}

        <Header></Header>
        
      </section>
    );
  }