import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const nicoMoji = localFont({
  src: "/fonts/NicoMoji-Regular.ttf",
  variable: "--font-nico-moji",
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nicoMoji.variable} antialiased overflow-hidden no-select`}
      >
        {children}
      </body>
    </html>
  );
}
